import { Box } from "@chakra-ui/react";
import Head from "next/head";
import HeroBg from "../assets/bg-hero.svg";
import Image from "next/image";
import Hero from "../components/Hero";
import Why from "../components/Why";
import About from "../components/About";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Forada</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<Why />
			<About />
		</div>
	);
}
